server:
  port: 7002
spring:
  application:
    name: gate
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true