server:
  port: 8080
spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://127.0.0.1:${server.port}/eureka